# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
User.create(username: "admin", firstname: "Admin", lastname: "SuperUser", registration: "000000",role: 2, password_digest: BCrypt::Password.create('*Sup.t1@'))
Office.create(name: "Analista Administrativo", user_id: 1)
Office.create(name: "Analista Contabil", user_id: 1)
Office.create(name: "Analista de Faturamento", user_id: 1)
Office.create(name: "Analista de Suporte", user_id: 1)
Office.create(name: "Analista Sistemas", user_id: 1)
Office.create(name: "Assistente Administrativo Diarista", user_id: 1)
Office.create(name: "Assistente Administrativo Plantonista Dia", user_id: 1)
Office.create(name: "Assistente Administrativo Plantonista Noite", user_id: 1)
Office.create(name: "Auxiliar Administrativo Diarista", user_id: 1)
Office.create(name: "Auxiliar Administrativo Plantonista Dia", user_id: 1)
Office.create(name: "Auxiliar Administrativo Plantonista Noite", user_id: 1)
Office.create(name: "Auxiliar Contabil", user_id: 1)
Office.create(name: "Auxiliar de Lavanderia Plantonista Dia", user_id: 1)
Office.create(name: "Auxiliar de Lavanderia Plantonista Noite", user_id: 1)
Office.create(name: "Auxiliar de serviços Gerais Plantonista Dia", user_id: 1)
Office.create(name: "Auxiliar de serviços Gerais Plantonista Noite", user_id: 1)
Office.create(name: "Auxiliar Diarista", user_id: 1)
Office.create(name: "Auxiliar Morgue Dia", user_id: 1)
Office.create(name: "Auxiliar Morgue Noite", user_id: 1)
Office.create(name: "Cabista", user_id: 1)
Office.create(name: "Controlador de Acesso Diarista", user_id: 1)
Office.create(name: "Controlador de Acesso Plantonista Dia", user_id: 1)
Office.create(name: "Controlador de Acesso Plantonista Norturno", user_id: 1)
Office.create(name: "Coordenador de Hotelaria", user_id: 1)
Office.create(name: "Coordenador de TI", user_id: 1)
Office.create(name: "Coordenador de Faturamento", user_id: 1)
Office.create(name: "Encarregada Diarista", user_id: 1)
Office.create(name: "Encarregada Plantonista Dia", user_id: 1)
Office.create(name: "Encarregada Plantonista Noite", user_id: 1)
Office.create(name: "Enfermeiro do Trabalho", user_id: 1)
Office.create(name: "Engenheiro de Segurança do Trabalho", user_id: 1)
Office.create(name: "Faturista", user_id: 1) 
Office.create(name: "Maqueiro Dia", user_id: 1)
Office.create(name: "Maqueiro Noite", user_id: 1)
Office.create(name: "Médico do Trabalho", user_id: 1)
Office.create(name: "Supervisor Administrativo", user_id: 1)
Office.create(name: "Supervisor Morgue", user_id: 1)
Office.create(name: "Técnico de Enfermagem do Trabalho", user_id: 1)
Office.create(name: "Técnico de Segurança do Trabalho", user_id: 1)
Office.create(name: "Técnico Diarista", user_id: 1)
Office.create(name: "Técnico Plantonista", user_id: 1)

Sectional.create(name: "Ambulatório", user_id: 1)
Sectional.create(name: "Apoio", user_id: 1)
Sectional.create(name: "Apoio Administrativo", user_id: 1)
Sectional.create(name: "Bloco Crítico", user_id: 1)
Sectional.create(name: "Centro Cirúrgico", user_id: 1)
Sectional.create(name: "Clínica Cirúrgica", user_id: 1)
Sectional.create(name: "Clínica Médica", user_id: 1)
Sectional.create(name: "Coordenação", user_id: 1)
Sectional.create(name: "CTI 1", user_id: 1)
Sectional.create(name: "CTI 2", user_id: 1)
Sectional.create(name: "CTI 3", user_id: 1)
Sectional.create(name: "CTI 4", user_id: 1)
Sectional.create(name: "CTI's", user_id: 1)
Sectional.create(name: "Doc Med", user_id: 1)
Sectional.create(name: "Eixo Vermelho", user_id: 1)
Sectional.create(name: "Emergência", user_id: 1)
Sectional.create(name: "Estacionamento", user_id: 1)
Sectional.create(name: "Faturamento", user_id: 1)
Sectional.create(name: "Garagem", user_id: 1)
Sectional.create(name: "Hipodermia/Ortopedia OS", user_id: 1)
Sectional.create(name: "Hipodermia/RX/Ortopedia", user_id: 1)
Sectional.create(name: "Informação", user_id: 1)
Sectional.create(name: "Medicina do Trabalho", user_id: 1)
Sectional.create(name: "Morgue", user_id: 1)
Sectional.create(name: "Neurocirurgia", user_id: 1)
Sectional.create(name: "NVH", user_id: 1)
Sectional.create(name: "Ortopedia", user_id: 1)
Sectional.create(name: "Patrimônio", user_id: 1)
Sectional.create(name: "Pediatria", user_id: 1)
Sectional.create(name: "Portaria Principal", user_id: 1)
Sectional.create(name: "Recepções/Coringa", user_id: 1)
Sectional.create(name: "Rendição", user_id: 1)
Sectional.create(name: "Rouparia", user_id: 1)
Sectional.create(name: "Sala Amarela/Vermelha", user_id: 1)
Sectional.create(name: "Sala Verde", user_id: 1)
Sectional.create(name: "SCIH", user_id: 1)
Sectional.create(name: "Segurança do Trabalho", user_id: 1)
Sectional.create(name: "SHL", user_id: 1)
Sectional.create(name: "SPA PED", user_id: 1)
Sectional.create(name: "Supervisão", user_id: 1)
Sectional.create(name: "Supervisão/Administração", user_id: 1)
Sectional.create(name: "TI", user_id: 1)
Sectional.create(name: "UPO", user_id: 1)

Sector.create(name:"Administrativos Clínicas", user_id: 1)
Sector.create(name:"Administrativos Emergência", user_id: 1)
Sector.create(name:"Agente de Portaria", user_id: 1)
Sector.create(name:"Arrecadação", user_id: 1)
Sector.create(name:"Documentação Médica", user_id: 1)
Sector.create(name:"Faturamento", user_id: 1)
Sector.create(name:"Maqueiro", user_id: 1)
Sector.create(name:"Morgue", user_id: 1)
Sector.create(name:"Patrimonio", user_id: 1)
Sector.create(name:"Recepções", user_id: 1)
Sector.create(name:"Rouparia", user_id: 1)
Sector.create(name:"SESMT", user_id: 1)
Sector.create(name:"SHL", user_id: 1)
Sector.create(name:"TI", user_id: 1)

Employee.create(registration:"7622", bond: 1, firstname: "Thiago", lastname: "Pinheiro", sector_id: 7, orderly: 0, sectional_id: 40, user_id: 1, office_id: 36)
Employee.create(registration:"6770", bond: 0, firstname: "Célio", lastname: "Barreto", sector_id: 7, orderly: 0, sectional_id: 40, user_id: 1, office_id: 36)
Employee.create(registration:"6810", bond: 0, firstname: "Eudes", lastname: "Santos", sector_id: 7, orderly: 0, sectional_id: 27, user_id: 1, office_id: 33)
Employee.create(registration:"7519", bond: 0, firstname: "Pedro", lastname: "Nascimento", sector_id: 7, orderly: 0, sectional_id: 7, user_id: 1, office_id: 33)
Employee.create(registration:"6368", bond: 0, firstname: "Claudio", lastname: "Silva", sector_id: 7, orderly: 0, sectional_id: 5, user_id: 1, office_id: 33)
Employee.create(registration:"6927", bond: 0, firstname: "Márcio", lastname: "Maia", sector_id: 7, orderly: 0, sectional_id: 4, user_id: 1, office_id: 33)
Employee.create(registration:"6444", bond: 0, firstname: "Humberto", lastname: "Silva", sector_id: 7, orderly: 0, sectional_id: 7, user_id: 1, office_id: 33)
Employee.create(registration:"8806", bond: 0, firstname: "Diego", lastname: "Melo", sector_id: 7, orderly: 0, sectional_id: 16, user_id: 1, office_id: 33)
Employee.create(registration:"6335", bond: 0, firstname: "Caio", lastname: "Silva", sector_id: 7, orderly: 0, sectional_id: 16, user_id: 1, office_id: 33)
Employee.create(registration:"7204", bond: 0, firstname: "Diego", lastname: "Lapa", sector_id: 7, orderly: 0, sectional_id: 16, user_id: 1, office_id: 33)
Employee.create(registration:"7422", bond: 0, firstname: "Marcelo", lastname: "Soares", sector_id: 7, orderly: 0, sectional_id: 16, user_id: 1, office_id: 33)
Employee.create(registration:"7450", bond: 0, firstname: "Vinícius", lastname: "Vieira", sector_id: 7, orderly: 0, sectional_id: 21, user_id: 1, office_id: 33)
Employee.create(registration:"7329", bond: 0, firstname: "Edson", lastname: "Barbosa", sector_id: 7, orderly: 0, sectional_id: 5, user_id: 1, office_id: 33)
Employee.create(registration:"10088", bond: 0, firstname: "Gustavo", lastname: "Santos", sector_id: 7, orderly: 0, sectional_id: 16, user_id: 1, office_id: 33)
Employee.create(registration:"10025", bond: 0, firstname: "Wallan", lastname: "Oliveira", sector_id: 7, orderly: 0, sectional_id: 16, user_id: 1, office_id: 33)
Employee.create(registration:"6315", bond: 0, firstname: "Anderson", lastname: "Pocinhos", sector_id: 7, orderly: 1, sectional_id: 16, user_id: 1, office_id: 34)
Employee.create(registration:"7070", bond: 0, firstname: "Wallace", lastname: "Rodrigues", sector_id: 7, orderly: 1, sectional_id: 16, user_id: 1, office_id: 34)
Employee.create(registration:"6345", bond: 0, firstname: "Carlos", lastname: "Silva", sector_id: 7, orderly: 1, sectional_id: 16, user_id: 1, office_id: 34)
Employee.create(registration:"6871", bond: 0, firstname: "Joaquim", lastname: "Filho", sector_id: 7, orderly: 1, sectional_id: 16, user_id: 1, office_id: 34)
Employee.create(registration:"7339", bond: 0, firstname: "José", lastname: "Silva", sector_id: 7, orderly: 1, sectional_id: 16, user_id: 1, office_id: 34)
Employee.create(registration:"6484", bond: 0, firstname: "Júlio", lastname: "Ramos", sector_id: 7, orderly: 1, sectional_id: 16, user_id: 1, office_id: 34)
Employee.create(registration:"7553", bond: 0, firstname: "Wesley", lastname: "Paciência", sector_id: 7, orderly: 1, sectional_id: 16, user_id: 1, office_id: 34)
Employee.create(registration:"6327", bond: 0, firstname: "Antonio", lastname: "Pereira", sector_id: 7, orderly: 0, sectional_id: 4, user_id: 1, office_id: 33)
Employee.create(registration:"7512", bond: 0, firstname: "Patrick", lastname: "Santos", sector_id: 7, orderly: 0, sectional_id: 16, user_id: 1, office_id: 33)
Employee.create(registration:"6449", bond: 0, firstname: "Itamar", lastname: "Mendes", sector_id: 7, orderly: 0, sectional_id: 7, user_id: 1, office_id: 33)
Employee.create(registration:"8987", bond: 0, firstname: "Luis", lastname: "Santana", sector_id: 7, orderly: 0, sectional_id: 16, user_id: 1, office_id: 33)
Employee.create(registration:"6512", bond: 0, firstname: "Luis", lastname: "Serra", sector_id: 7, orderly: 0, sectional_id: 5, user_id: 1, office_id: 33)
Employee.create(registration:"7469", bond: 0, firstname: "Max", lastname: "Barros", sector_id: 7, orderly: 0, sectional_id: 16, user_id: 1, office_id: 33)
Employee.create(registration:"6693", bond: 0, firstname: "Tiago", lastname: "Lima", sector_id: 7, orderly: 0, sectional_id: 5, user_id: 1, office_id: 33)
Employee.create(registration:"7812", bond: 0, firstname: "Waldecir", lastname: "Belisário", sector_id: 7, orderly: 0, sectional_id: 16, user_id: 1, office_id: 33)
Employee.create(registration:"7252", bond: 0, firstname: "Thiago", lastname: "Souza", sector_id: 7, orderly: 0, sectional_id: 16, user_id: 1, office_id: 33)
Employee.create(registration:"7409", bond: 0, firstname: "Valdir", lastname: "Barbosa", sector_id: 7, orderly: 0, sectional_id: 27, user_id: 1, office_id: 33)
Employee.create(registration:"9334", bond: 0, firstname: "Thiago", lastname: "Campello", sector_id: 7, orderly: 0, sectional_id: 21, user_id: 1, office_id: 33)
Employee.create(registration:"7041", bond: 0, firstname: "Vandeir", lastname: "Silva", sector_id: 7, orderly: 0, sectional_id: 7, user_id: 1, office_id: 33)
Employee.create(registration:"8461", bond: 0, firstname: "Jamil", lastname: "Silva", sector_id: 7, orderly: 0, sectional_id: 16, user_id: 1, office_id: 33)
Employee.create(registration:"7203", bond: 0, firstname: "Diego", lastname: "Santos", sector_id: 7, orderly: 1, sectional_id: 16, user_id: 1, office_id: 34)
Employee.create(registration:"6423", bond: 0, firstname: "Fabio", lastname: "Silva", sector_id: 7, orderly: 1, sectional_id: 16, user_id: 1, office_id: 34)
Employee.create(registration:"7245", bond: 0, firstname: "Fabiano", lastname: "Pinheiro", sector_id: 7, orderly: 1, sectional_id: 16, user_id: 1, office_id: 34)
Employee.create(registration:"6201", bond: 0, firstname: "Adriano", lastname: "Nascimento", sector_id: 7, orderly: 1, sectional_id: 16, user_id: 1, office_id: 34)
Employee.create(registration:"10112", bond: 0, firstname: "Josean", lastname: "Oliveira", sector_id: 7, orderly: 1, sectional_id: 16, user_id: 1, office_id: 34)
Employee.create(registration:"8513", bond: 0, firstname: "Luciano", lastname: "Oliveira", sector_id: 7, orderly: 1, sectional_id: 3, user_id: 1, office_id: 34)
Employee.create(registration:"9019", bond: 0, firstname: "Humberto", lastname: "Ferreira", sector_id: 7, orderly: 1, sectional_id: 16, user_id: 1, office_id: 34)
Employee.create(registration:"6422", bond: 1, firstname: "Fábio", lastname: "Souza", sector_id: 3, orderly: 0, sectional_id: 28, user_id: 1, office_id: 36)
Employee.create(registration:"6911", bond: 1, firstname: "Luis", lastname: "Brito", sector_id: 3, orderly: 0, sectional_id: 19, user_id: 1, office_id: 22)
Employee.create(registration:"7850", bond: 1, firstname: "Márcio", lastname: "Borges", sector_id: 3, orderly: 0, sectional_id: 1, user_id: 1, office_id: 22)
Employee.create(registration:"8435", bond: 1, firstname: "Marco", lastname: "Moraes", sector_id: 3, orderly: 0, sectional_id: 30, user_id: 1, office_id: 22)
Employee.create(registration:"9765", bond: 1, firstname: "Dandara", lastname: "Torres", sector_id: 3, orderly: 0, sectional_id: 17, user_id: 1, office_id: 22)
Employee.create(registration:"7396", bond: 1, firstname: "Lourenço", lastname: "Neto", sector_id: 3, orderly: 0, sectional_id: 32, user_id: 1, office_id: 22)
Employee.create(registration:"6328", bond: 1, firstname: "Antonio", lastname: "Carvalho", sector_id: 3, orderly: 0, sectional_id: 30, user_id: 1, office_id: 22)
Employee.create(registration:"6617", bond: 1, firstname: "Reginaldo", lastname: "Silva", sector_id: 3, orderly: 0, sectional_id: 22, user_id: 1, office_id: 21)
Employee.create(registration:"10087", bond: 1, firstname: "Rodrigo", lastname: "Brito", sector_id: 3, orderly: 0, sectional_id: 15, user_id: 1, office_id: 22)
Employee.create(registration:"7064", bond: 1, firstname: "Adriano", lastname: "Santos", sector_id: 3, orderly: 1, sectional_id: 19, user_id: 1, office_id: 23)
Employee.create(registration:"9335", bond: 1, firstname: "Edson", lastname: "Junior", sector_id: 3, orderly: 1, sectional_id: 32, user_id: 1, office_id: 23)
Employee.create(registration:"6820", bond: 1, firstname: "Fernando", lastname: "Nascimento", sector_id: 3, orderly: 1, sectional_id: 22, user_id: 1, office_id: 23)
Employee.create(registration:"8192", bond: 1, firstname: "Geovane", lastname: "Silva", sector_id: 3, orderly: 1, sectional_id: 19, user_id: 1, office_id: 23)
Employee.create(registration:"6981", bond: 1, firstname: "Raphael", lastname: "Souza", sector_id: 3, orderly: 1, sectional_id: 15, user_id: 1, office_id: 23)
Employee.create(registration:"6967", bond: 1, firstname: "Nesvaldo", lastname: "Alves", sector_id: 3, orderly: 1, sectional_id: 17, user_id: 1, office_id: 23)
Employee.create(registration:"6762", bond: 1, firstname: "Bruno", lastname: "Santos", sector_id: 3, orderly: 0, sectional_id: 15, user_id: 1, office_id: 21)
Employee.create(registration:"6897", bond: 1, firstname: "Leonardo", lastname: "Oliveira", sector_id: 3, orderly: 0, sectional_id: 17, user_id: 1, office_id: 22)
Employee.create(registration:"7569", bond: 1, firstname: "Sérgio", lastname: "Cardoso", sector_id: 3, orderly: 0, sectional_id: 30, user_id: 1, office_id: 22)
Employee.create(registration:"6955", bond: 1, firstname: "Misael", lastname: "Santos", sector_id: 3, orderly: 0, sectional_id: 30, user_id: 1, office_id: 22)
Employee.create(registration:"6996", bond: 1, firstname: "Ronald", lastname: "Santos", sector_id: 3, orderly: 0, sectional_id: 32, user_id: 1, office_id: 22)
Employee.create(registration:"9818", bond: 1, firstname: "Novenjulio", lastname: "silva", sector_id: 3, orderly: 0, sectional_id: 19, user_id: 1, office_id: 22)
Employee.create(registration:"6997", bond: 1, firstname: "Ronald", lastname: "Souza", sector_id: 3, orderly: 0, sectional_id: 22, user_id: 1, office_id: 22)
Employee.create(registration:"6334", bond: 1, firstname: "Bruno", lastname: "Lima", sector_id: 3, orderly: 1, sectional_id: 15, user_id: 1, office_id: 23)
Employee.create(registration:"9196", bond: 1, firstname: "Pedro", lastname: "Dias", sector_id: 3, orderly: 1, sectional_id: 17, user_id: 1, office_id: 23)
Employee.create(registration:"6464", bond: 1, firstname: "João", lastname: "Filho", sector_id: 3, orderly: 1, sectional_id: 32, user_id: 1, office_id: 23)
Employee.create(registration:"6601", bond: 1, firstname: "Paulo", lastname: "Ferreira", sector_id: 3, orderly: 1, sectional_id: 22, user_id: 1, office_id: 23)
Employee.create(registration:"8825", bond: 1, firstname: "Marco", lastname: "Andrade", sector_id: 3, orderly: 1, sectional_id: 19, user_id: 1, office_id: 23)
Employee.create(registration:"6746", bond: 1, firstname: "André", lastname: "Machado", sector_id: 3, orderly: 1, sectional_id: 17, user_id: 1, office_id: 23)
Employee.create(registration:"7098", bond: 1, firstname: "Ana", lastname: " Gil", sector_id: 10, orderly: 0, sectional_id: 41, user_id: 1, office_id: 36)
Employee.create(registration:"9693", bond: 1, firstname: "Evandro", lastname: " Soares", sector_id: 10, orderly: 0, sectional_id: 41, user_id: 1, office_id: 6)
Employee.create(registration:"6435", bond: 1, firstname: "Gabriella", lastname: " Silva", sector_id: 10, orderly: 0, sectional_id: 1, user_id: 1, office_id: 9)
Employee.create(registration:"8028", bond: 1, firstname: "Milena", lastname: " Lobianco", sector_id: 10, orderly: 0, sectional_id: 1, user_id: 1, office_id: 9)
Employee.create(registration:"6822", bond: 1, firstname: "Flávia", lastname: " Lisboa", sector_id: 10, orderly: 0, sectional_id: 1, user_id: 1, office_id: 9)
Employee.create(registration:"8232", bond: 1, firstname: "Ana", lastname: " Michel", sector_id: 10, orderly: 0, sectional_id: 1, user_id: 1, office_id: 9)
Employee.create(registration:"7364", bond: 1, firstname: "Jurema", lastname: " Dias", sector_id: 10, orderly: 1, sectional_id: 2, user_id: 1, office_id: 11)
Employee.create(registration:"7449", bond: 1, firstname: "Maria", lastname: " Mathias", sector_id: 10, orderly: 0, sectional_id: 2, user_id: 1, office_id: 10)
Employee.create(registration:"7467", bond: 1, firstname: "Mateus", lastname: " Tomaz", sector_id: 10, orderly: 1, sectional_id: 2, user_id: 1, office_id: 11)
Employee.create(registration:"7467", bond: 1, firstname: "Mateus", lastname: " Tomaz", sector_id: 10, orderly: 0, sectional_id: 2, user_id: 1, office_id: 10)
Employee.create(registration:"7502", bond: 1, firstname: "Nilson", lastname: " Souza", sector_id: 10, orderly: 0, sectional_id: 2, user_id: 1, office_id: 10)
Employee.create(registration:"6578", bond: 1, firstname: "Natália", lastname: " Souza", sector_id: 10, orderly: 0, sectional_id: 31, user_id: 1, office_id: 7)
Employee.create(registration:"8673", bond: 1, firstname: "Ana", lastname: " Santos", sector_id: 10, orderly: 0, sectional_id: 15, user_id: 1, office_id: 10)
Employee.create(registration:"8433", bond: 1, firstname: "Joana", lastname: " Conceição", sector_id: 10, orderly: 0, sectional_id: 22, user_id: 1, office_id: 10)
Employee.create(registration:"7846", bond: 1, firstname: "Alessandra", lastname: " Silva", sector_id: 10, orderly: 0, sectional_id: 31, user_id: 1, office_id: 10)
Employee.create(registration:"8672", bond: 1, firstname: "Irini", lastname: " Duarte", sector_id: 10, orderly: 0, sectional_id: 30, user_id: 1, office_id: 10)
Employee.create(registration:"10086", bond: 1, firstname: "Beatriz", lastname: " Oliveira", sector_id: 10, orderly: 0, sectional_id: 30, user_id: 1, office_id: 11)
Employee.create(registration:"9813", bond: 1, firstname: "Maria", lastname: " Sheraphini", sector_id: 10, orderly: 0, sectional_id: 30, user_id: 1, office_id: 11)
Employee.create(registration:"6848", bond: 1, firstname: "Iolanda", lastname: " Amorim", sector_id: 10, orderly: 1, sectional_id: 31, user_id: 1, office_id: 8)
Employee.create(registration:"7161", bond: 1, firstname: "Célia", lastname: " Silva", sector_id: 10, orderly: 1, sectional_id: 22, user_id: 1, office_id: 11)
Employee.create(registration:"6313", bond: 1, firstname: "Anderson", lastname: " Alves", sector_id: 10, orderly: 1, sectional_id: 19, user_id: 1, office_id: 11)
Employee.create(registration:"9580", bond: 1, firstname: "Wallace", lastname: " Moreira", sector_id: 10, orderly: 1, sectional_id: 15, user_id: 1, office_id: 11)
Employee.create(registration:"9224", bond: 1, firstname: "Márcio", lastname: " Netto", sector_id: 10, orderly: 1, sectional_id: 15, user_id: 1, office_id: 11)
Employee.create(registration:"7440", bond: 1, firstname: "Marcos", lastname: " Silva", sector_id: 10, orderly: 0, sectional_id: 31, user_id: 1, office_id: 7)
Employee.create(registration:"7040", bond: 1, firstname: "Vandalea", lastname: " Oliveira", sector_id: 10, orderly: 0, sectional_id: 22, user_id: 1, office_id: 10)
Employee.create(registration:"6943", bond: 1, firstname: "Maria", lastname: " Barbosa", sector_id: 10, orderly: 0, sectional_id: 15, user_id: 1, office_id: 10)
Employee.create(registration:"10084", bond: 1, firstname: "Matheus", lastname: " Rosa", sector_id: 10, orderly: 0, sectional_id: 15, user_id: 1, office_id: 10)
Employee.create(registration:"8991", bond: 1, firstname: "Bárbara", lastname: " Silva", sector_id: 10, orderly: 0, sectional_id: 19, user_id: 1, office_id: 10)
Employee.create(registration:"6850", bond: 1, firstname: "Isabela", lastname: " Barbosa", sector_id: 10, orderly: 0, sectional_id: 30, user_id: 1, office_id: 10)
Employee.create(registration:"8237", bond: 1, firstname: "Ingrid", lastname: " Silva", sector_id: 10, orderly: 0, sectional_id: 30, user_id: 1, office_id: 10)
Employee.create(registration:"9728", bond: 1, firstname: "Isabella", lastname: " mello", sector_id: 10, orderly: 0, sectional_id: 30, user_id: 1, office_id: 9)
Employee.create(registration:"7730", bond: 1, firstname: "Jefferson", lastname: " Clemente", sector_id: 10, orderly: 1, sectional_id: 31, user_id: 1, office_id: 8)
Employee.create(registration:"6908", bond: 1, firstname: "Lucimara", lastname: " Silva", sector_id: 10, orderly: 1, sectional_id: 22, user_id: 1, office_id: 11)
Employee.create(registration:"8239", bond: 1, firstname: "Jaqueline", lastname: " Santos", sector_id: 10, orderly: 1, sectional_id: 19, user_id: 1, office_id: 11)
Employee.create(registration:"6785", bond: 1, firstname: "Cristina", lastname: " Vieira", sector_id: 10, orderly: 1, sectional_id: 15, user_id: 1, office_id: 11)
Employee.create(registration:"9679", bond: 1, firstname: "Leonardo", lastname: " Silva", sector_id: 10, orderly: 1, sectional_id:15, user_id: 1, office_id:11)