# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Office.create(name: "Analista Administrativo", user_id: 1)
Office.create(name: "Analista Contabil", user_id: 1)
Office.create(name: "Analista de Faturamento", user_id: 1)
Office.create(name: "Analista de Suporte", user_id: 1)
Office.create(name: "Analista Sistemas", user_id: 1)
Office.create(name: "Assistente Administrativo Diarista", user_id: 1)
Office.create(name: "Assistente Administrativo Plantonista Dia", user_id: 1)
Office.create(name: "Assistente Administrativo Plantonista Noite", user_id: 1)
Office.create(name: "Auxiliar Administrativo Diarista", user_id: 1)
Office.create(name: "Auxiliar Administrativo Plantonista Dia", user_id: 1)
Office.create(name: "Auxiliar Administrativo Plantonista Noite", user_id: 1)
Office.create(name: "Auxiliar Contabil", user_id: 1)
Office.create(name: "Auxiliar de Lavanderia Plantonista Dia", user_id: 1)
Office.create(name: "Auxiliar de Lavanderia Plantonista Noite", user_id: 1)
Office.create(name: "Auxiliar de serviços Gerais Plantonista Dia", user_id: 1)
Office.create(name: "Auxiliar de serviços Gerais Plantonista Noite", user_id: 1)
Office.create(name: "Auxiliar Diarista", user_id: 1)
Office.create(name: "Auxiliar Morgue Dia", user_id: 1)
Office.create(name: "Auxiliar Morgue Noite", user_id: 1)
Office.create(name: "Cabista", user_id: 1)
Office.create(name: "Controlador de Acesso Diarista", user_id: 1)
Office.create(name: "Controlador de Acesso Plantonista Dia", user_id: 1)
Office.create(name: "Controlador de Acesso Plantonista Norturno", user_id: 1)
Office.create(name: "Coordenador de Hotelaria", user_id: 1)
Office.create(name: "Coordenador de TI", user_id: 1)
Office.create(name: "Coordenador de Faturamento", user_id: 1)
Office.create(name: "Encarregada Diarista", user_id: 1)
Office.create(name: "Encarregada Plantonista Dia", user_id: 1)
Office.create(name: "Encarregada Plantonista Noite", user_id: 1)
Office.create(name: "Enfermeiro do Trabalho", user_id: 1)
Office.create(name: "Engenheiro de Segurança do Trabalho", user_id: 1)
Office.create(name: "Faturista", user_id: 1) 
Office.create(name: "Maqueiro Dia", user_id: 1)
Office.create(name: "Maqueiro Noite", user_id: 1)
Office.create(name: "Médico do Trabalho", user_id: 1)
Office.create(name: "Supervisor Administrativo", user_id: 1)
Office.create(name: "Supervisor Morgue", user_id: 1)
Office.create(name: "Técnico de Enfermagem do Trabalho", user_id: 1)
Office.create(name: "Técnico de Segurança do Trabalho", user_id: 1)
Office.create(name: "Técnico Diarista", user_id: 1)
Office.create(name: "Técnico Plantonista", user_id: 1)

Sectional.create(name: "Ambulatório", user_id: 1)
Sectional.create(name: "Apoio", user_id: 1)
Sectional.create(name: "Apoio Administrativo", user_id: 1)
Sectional.create(name: "Bloco Crítico", user_id: 1)
Sectional.create(name: "Centro Cirúrgico", user_id: 1)
Sectional.create(name: "Clínica Cirúrgica", user_id: 1)
Sectional.create(name: "Clínica Médica", user_id: 1)
Sectional.create(name: "Coordenação", user_id: 1)
Sectional.create(name: "CTI 1", user_id: 1)
Sectional.create(name: "CTI 2", user_id: 1)
Sectional.create(name: "CTI 3", user_id: 1)
Sectional.create(name: "CTI 4", user_id: 1)
Sectional.create(name: "CTI's", user_id: 1)
Sectional.create(name: "Doc Med", user_id: 1)
Sectional.create(name: "Eixo Vermelho", user_id: 1)
Sectional.create(name: "Emergência", user_id: 1)
Sectional.create(name: "Estacionamento", user_id: 1)
Sectional.create(name: "Faturamento", user_id: 1)
Sectional.create(name: "Garagem", user_id: 1)
Sectional.create(name: "Hipodermia/Ortopedia OS", user_id: 1)
Sectional.create(name: "Hipodermia/RX/Ortopedia", user_id: 1)
Sectional.create(name: "Informação", user_id: 1)
Sectional.create(name: "Medicina do Trabalho", user_id: 1)
Sectional.create(name: "Morgue", user_id: 1)
Sectional.create(name: "Neurocirurgia", user_id: 1)
Sectional.create(name: "NVH", user_id: 1)
Sectional.create(name: "Ortopedia", user_id: 1)
Sectional.create(name: "Patrimônio", user_id: 1)
Sectional.create(name: "Pediatria", user_id: 1)
Sectional.create(name: "Portaria Principal", user_id: 1)
Sectional.create(name: "Recepções/Coringa", user_id: 1)
Sectional.create(name: "Rendição", user_id: 1)
Sectional.create(name: "Rouparia", user_id: 1)
Sectional.create(name: "Sala Amarela/Vermelha", user_id: 1)
Sectional.create(name: "Sala Verde", user_id: 1)
Sectional.create(name: "SCIH", user_id: 1)
Sectional.create(name: "Segurança do Trabalho", user_id: 1)
Sectional.create(name: "SHL", user_id: 1)
Sectional.create(name: "SPA PED", user_id: 1)
Sectional.create(name: "Supervisão", user_id: 1)
Sectional.create(name: "Supervisão/Administração", user_id: 1)
Sectional.create(name: "TI", user_id: 1)
Sectional.create(name: "UPO", user_id: 1)

Sector.create(name:"Administrativos Clínicas", user_id: 1)
Sector.create(name:"Administrativos Emergência", user_id: 1)
Sector.create(name:"Agente de Portaria", user_id: 1)
Sector.create(name:"Arrecadação", user_id: 1)
Sector.create(name:"Documentação Médica", user_id: 1)
Sector.create(name:"Faturamento", user_id: 1)
Sector.create(name:"Maqueiro", user_id: 1)
Sector.create(name:"Morgue", user_id: 1)
Sector.create(name:"Patrimonio", user_id: 1)
Sector.create(name:"Recepções", user_id: 1)
Sector.create(name:"Rouparia", user_id: 1)
Sector.create(name:"SESMT", user_id: 1)
Sector.create(name:"SHL", user_id: 1)
Sector.create(name:"TI", user_id: 1)